### PR TITLE
parsing an empty string as an Authority returns an error

### LINKED ISSUE #163: Parsing Authority with an empty string should be an error
Consider:

```rust
let auth = "".parse::<Authority>().unwrap();
```

That currently succeeds, and gives you an `Authority` that is blank. If you then try to construct a `Uri` with it, by using `uri::Parts`, and then to string it, you can end up with `http:///`, which is clearly wrong.

### PR DESCRIPTION
**Pull request by seanmonstar**
Closes #163

### CODE REVIEW

File: src/uri/authority.rs [hunk 1]
```diff
@@ -53,6 +53,7 @@ impl Authority {
         })
     }
 
+    // Note: this may return an *empty* Authority. You might want `parse_non_empty`.
     pub(super) fn parse(s: &[u8]) -> Result<usize, InvalidUri> {
```
Comment (carllerche) [inline src/uri/authority.rs]: This looks to be crate private. Is there a reason the caller could pass in an empty authority?

Comment (seanmonstar) [reply src/uri/authority.rs]: Yes, there is, in `parse_full` for `Uri`. An empty authority is handled differently there (error is `MissingAuthority` instead of `Empty`).
